#!/bin/bash

TAG=${1}
VALID_TAG=false
MAIN_ONLY=true

if [ "x${TAG}" == "x" ]; then
  echo "You must specify a tag"
  exit 10
fi

if [ ! -f "VERSION" ]; then
  echo "This script should be run from the root of the directory"
  exit 11
fi

BRANCH=$(git symbolic-ref HEAD 2> /dev/null)
BRANCH=${BRANCH##refs/heads/}

if echo "${TAG}" | grep -qE "^[0-9]+\.[0-9]+\.[0-9]+$"; then
  VALID_TAG=true
fi

if echo "${TAG}" | grep -qE "^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$"; then
  VALID_TAG=true
  MAIN_ONLY=false
fi

if echo "${TAG}" | grep -qE "^[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$"; then
  VALID_TAG=true
  MAIN_ONLY=false
fi

if [ "${BRANCH}" != "main" ] && [ "${MAIN_ONLY}" == "true" ]; then
  echo "You must only be on the main branch"
  exit 12
fi

if [ "${VALID_TAG}" == "false" ]; then
  echo "The tag specified was invalid."
  exit 10
fi

VTAG="v${TAG}"
MSG="version: ${TAG}"

echo "$TAG" > VERSION

if [ -f chart/Chart.yaml ]; then
  sed -i.bak "s/appVersion: .*/appVersion: ${TAG}/g" chart/Chart.yaml
  sed -i.bak "s/tag: .*/tag: ${VTAG}/g" chart/values.yaml
  rm chart/*.bak
fi

if [ -f pkg/common/version.go ]; then
  sed -i.bak "s/var VERSION = .*/var VERSION = \"${TAG}\"/g" pkg/common/version.go
  rm pkg/common/*.bak
fi

git commit -a -m "${MSG}"
git tag -m "${MSG}" "${VTAG}"
git push --follow-tags origin "${BRANCH}"
