apiVersion: v1
kind: Service
metadata:
  labels:
    goatlas.io/cluster: "true"
    goatlas.io/replicas: "2"
  generateName: downstream-cluster-
  namespace: monitoring
spec:
  clusterIP: None
  clusterIPs:
    - None
  externalIPs:
    - 2.137.36.224
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: 10901
    - name: http
      port: 10902
      protocol: TCP
      targetPort: 10902
