apiVersion: v1
kind: Service
metadata:
  labels:
    goatlas.io/cluster: "true"
    goatlas.io/thanos-sidecar: "0"
  name: downstream-cluster-name-thanos-sidecarN
  namespace: monitoring
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: 10901
    - name: http
      port: 10902
      protocol: TCP
      targetPort: 10902
  selector:
    app: envoy
    release: thanos-envoy
  sessionAffinity: None
  type: ClusterIP
