---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-coredns
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        prometheus :9153
        cache 30
        loop
        log
        reload
        loadbalance
        file /etc/coredns-zones/atlas.zone atlas {
          reload 30s
        }
    }
  atlas.zone: |
    $ORIGIN atlas.
    @	3600 IN	SOA ns.atlas. postmaster.atlas. (
            1 ; serial
            7200       ; refresh (2 hours)
            3600       ; retry (1 hour)
            1209600    ; expire (2 weeks)
            3600       ; minimum (1 hour)
            )
