apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-envoy-ads
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 6305
    protocol: TCP
    targetPort: 6305
    name: grpc
  selector:
    app: {{ include "app.name" . }}
    release: {{ .Release.Name }}
    component: envoy-ads
